export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";


export const STORE_PROFILE_SUCCESS = "STORE_PROFILE_SUCCESS"
export const STORE_PROFILE_FAIL = "STORE_PROFILE_FAIL";
export const STORE_USER_STATUS = "STORE_USER_STATUS";

export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS"
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL"
