export const AUTH_INIT = "AUTH_INIT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_RESET_ERROR = "AUTH_RESET_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const LOAD_PROFILE_INIT = "LOAD_INIT";
export const UPDATE_PROFILE_INIT = "UPDATE_INIT";
export const UPDATE_PROFILE_SUCCESS = "STORE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "STORE_PROFILE_FAIL";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const FETCH_SELF_POSTS_INIT = 'FETCH_SELF_POSTS_INIT'
export const FETCH_SELF_POSTS_SUCCESS = 'FETCH_SELF_POSTS_SUCCESS'
export const FETCH_SELF_POSTS_FAIL = 'FETCH_SELF_POSTS_FAIL'
export const FETCH_FRIENDS_POSTS_INIT = 'FETCH_FRIENDS_POSTS_INIT'
export const FETCH_FRIENDS_POSTS_SUCCESS = 'FETCH_FRIENDS_POSTS_SUCCESS'
export const FETCH_FRIENDS_POSTS_FAIL = 'FETCH_FRIENDS_POSTS_FAIL'
export const ADD_POST_INIT = "ADD_POST_INIT";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const FETCH_USERS_INIT = "FETCH_USERS_INIT";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const FETCH_FRIENDS_INIT = "FETCH_FRIENDS_INIT";
export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const FETCH_FRIENDS_FAIL = "FETCH_FRIENDS_FAIL";


